###
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/ads/traffic/?start_time=2020-03-25T08:57:04.428Z&end_time=2021-03-23T08:57:04.428Z
Accept: application/json
Authorization: {{authorization}}

###



###------------------------------ smg ----------------------------



####
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/nta/traffic/?chart=area&unit=bps&sortby=avg&start_time=2020-07-31T08%3A31%3A25.869Z&end_time=2020-07-31T09%3A31%3A25.869Z
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/ads/eventduration/?start_time=2020-07-31T08%3A31%3A25.869Z&end_time=2020-07-31T09%3A31%3A25.869Z
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/10/monitor/ads/eventdistr/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/2/monitor/nta/eventsrcporttopn/?device_ip=10.66.243.230&event_id=7176885487358737269&start_time=2021-01-01T07%3A02%3A27.000Z&end_time=2021-01-31T10%3A50%3A52.768Z
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/40/monitor/genieatm/traffic/?device_ip=10.66.243.230&event_id=7176885487358737269&start_time=2021-02-01T07%3A02%3A27.000Z&end_time=2021-02-28T10%3A50%3A52.768Z
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/monitor/atic_mitigation/traffic/?start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.1
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/monitor/atic_mitigation/topn/?sortby=In&topn=5&start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.1
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/monitor/atic_mitigation/events/?orderby=time&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/monitor/atic_mitigation/eventtypesdistr/?orderby=bps&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###



#------------------- SMP ----------------------


###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/points/1/monitor/atic_mitigation/topn/?sortby=In&topn=5&start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.1
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/points/1/monitor/atic_mitigation/traffic/?start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###


#-------------------sz traffic----------------------


### Scrubbing Zones
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/traffic/?start_time=2020-03-23T08:57:04.428Z&end_time=2020-03-23T08:57:04.428Z
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/events/?limit=10&offset=0&start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/eventtypesdistr/?limit=10&offset=0
Accept: application/json
Authorization: {{authorization}}

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/topn/?sortby=In
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/traffic/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/topn/?sortby=Inbound&topn=5&start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/abnormaltopn/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/events/?limit=10&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/eventtypesdistr/?limit=5&offset=0
Accept: application/json
Authorization: {{authorization}}

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/atic_mitigation/traffic/?start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/atic_mitigation/topn/?sortby=In&topn=5&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-12T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/atic_mitigation/traffic/?start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/atic_mitigation/events/?orderby=time&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/atic_mitigation/eventtypesdistr/?orderby=bps&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###

#-------------------SN traffic----------------------

### Scrubbing Nodes

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/traffic/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z&dstip=1.1.1.1
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/topn/?sortby=In
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/events/?limit=3&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/eventtypesdistr/
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/traffic/?start_time=2020-02-23T08:00:00.000Z&end_time=2020-03-23T08:57:04.428Z&dstip=80.94.22.100
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/topn/?sortby=Inbound&topn=5&start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z&topn=5
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/events/?limit=3&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/eventtypesdistr/?limit=5&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/abnormaltopn/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/atic_mitigation/topn/?sortby=In&topn=5&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-12T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/atic_mitigation/traffic/?start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/atic_mitigation/events/?orderby=time&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/atic_mitigation/eventtypesdistr/?orderby=bps&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###

#-------------------SE traffic----------------------

###
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/atic_mitigation/topn/?sortby=In&topn=5&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-12T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/atic_mitigation/traffic/?start_time=2021-03-02T08:00:00.000Z&end_time=2021-03-02T09:57:04.428Z&dstip=1.1.1.2
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/atic_mitigation/events/?orderby=time&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/v1/scrubbingenvironments/1/monitor/atic_mitigation/eventtypesdistr/?orderby=bps&start_time=2021-03-02T08:00:00.000Z&end_time=2021-04-15T09:57:04.428Z&dstip=1.1.1.1&limit=5&offset=0
Authorization: {{authorization}}
Accept: application/json

###