###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/28/monitor/ads/events/?orderby=-bps HTTP/3.5
Accept: application/json
Authorization: {{authorization}}

###3rd service shanghai telecom
GET http://{{host}}:{{port}}/api/v1/3rdservices/baiducloud/account/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###

GET http://{{host}}:{{port}}/api/v1/dialtestdeploy/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
POST http://{{host}}:{{port}}/api/v1/scrubbingzones/
Accept: application/json
Authorization: {{authorization}}
Content-Type: application/json

{
  "name": "test111",
  "scrubbing_environment": "16"
}

###

PUT http://{{host}}:{{port}}/api/v1/smtpconfig/1/
Authorization: {{authorization}}
Content-Type: application/json

{
  "server_address": "0.0.0.1",
  "server_port": 25,
  "sender_email": "admin@example.com",
  "auth_enabled": false
}

###

POST http://{{host}}:{{port}}/api/v1/smtpconfig/test/
Authorization: {{authorization}}
Content-Type: application/json

{
  "receiver": ""
}

###

GET http://{{host}}:{{port}}/api/v1/usergroups/
Content-Type: application/json
Authorization: {{authorization}}

###

POST http://{{host}}:{{port}}/api/v1/users/
Content-Type: application/json
Authorization: {{authorization}}

{
  "user_groups": [
    1234
  ],
  "account": "18702869172",
  "username": "socdemo111",
  "email": "hr_chy@qq.com",
  "phone": "18702869172",
  "password": "IJViLHEsFnOjgIZf5iOEP4hv5yFnB6GUozi+rWMiBF6ULxHHVKpA1f20R5gdrBn/NZsO38ocEdrX9mOR4nxWPlCGQfRvNxjFqGwg/+JHs66/TJagrEzNyrUE9uLoLVoFm+14J/9O6GjbRq6WBN29qjPlVmjTiVjeOos4gXq05Ip4tCW7stF+W5JIfBXElpiaxwETzZBOihBUe4WMLQJQ9NZTh2og0m5ya+5e0tcfQrl0hU1BHZP5kgaM2vmuowx31b6oj9iZE/rljhJXvo7QUx/lU6+ViNmzeWRHpnoWYGN0VLgtgqwWSsou+KGuDm8mISVmk7NGXsm6+J5LEszfZw==",
  "encrypted": false
}



###


#-------------------smg traffic----------------------

#### Scrubbing monitor group

GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###

GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/monitor/ads/devicetraffic/?device_ip=10.66.250.185&start_time=2020-02-19T16:00:00.000Z&end_time=2020-03-20T09:01:05.713Z
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###

GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/monitor/ads/devicetrafficstable/?sortby=-curpassbps&start_time=2020-02-19T16:00:00.000Z&end_time=2020-03-20T09:01:05.713Z&limit=10&offset=0
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###

GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/points/1/monitor/ads/devicetraffics/?device_ip=10.66.250.185&start_time=2020-02-19T16:00:00.000Z&end_time=2020-03-20T09:01:05.713Z
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###

GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/points/1/monitor/ads/devicetrafficstable/?sortby=-curpassbps&start_time=2020-02-19T16:00:00.000Z&end_time=2020-03-20T09:01:05.713Z&limit=10&offset=0
Accept: application/json
Authorization: {{authorization}}
accept-language: en


###


#-------------------smg src ip topn----------------------

#### Scrubbing monitor group
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/37/monitor/ads/srctopn/?sortby=In&char=bar&start_time=2020-08-12T16:00:00.000Z&end_time=2020-08-12T19:01:05.713Z&l&topn=5
Accept: application/json
Authorization: {{authorization}}
accept-language: en




###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/36/monitor/ads/srctopngeodist/?sortby=In&char=bar&start_time=2020-07-12T16:00:00.000Z&end_time=2020-08-12T19:01:05.713Z&l&topn=5
Accept: application/json
Authorization: {{authorization}}
accept-language: en




###

#-------------------smp----------------------


###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/3/points/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

###
PUT http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/3/points/4/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

{"id":4,"name":"SMP-106244","domain":[],"iprange":["106.31.24.0/24"],"scrubbing_monitor_group":3}

###
POST http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/3/points/
Accept: application/json
Authorization: {{authorization}}
accept-language: en

{"name":"test","iprange":["106.31.24.0/25"],"scrubbing_monitor_group":3}

###


#-------------------sz traffic----------------------


### Scrubbing Zones

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/traffic/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/events/?limit=10&offset=0&start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/eventtypesdistr/?limit=10&offset=0
Accept: application/json
Authorization: {{authorization}}

###
GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/ads/topn/?sortby=In
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/traffic/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/topn/?sortby=Inbound&topn=5&start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/abnormaltopn/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/events/?limit=10&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingzones/1/monitor/nta/eventtypesdistr/?limit=5&offset=0
Accept: application/json
Authorization: {{authorization}}

###

#-------------------sn traffic----------------------

### Scrubbing Nodes

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/traffic/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z&dstip=1.1.1.1
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/topn/?sortby=In
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/events/?limit=3&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/ads/eventtypesdistr/
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/traffic/?start_time=2020-02-23T08:00:00.000Z&end_time=2020-03-23T08:57:04.428Z&dstip=80.94.22.100
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/topn/?sortby=Inbound&topn=5&start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z&topn=5
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/events/?limit=3&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/eventtypesdistr/?limit=5&offset=0
Accept: application/json
Authorization: {{authorization}}

###

GET http://{{host}}:{{port}}/api/v1/scrubbingnodes/1/monitor/nta/abnormaltopn/?start_time=2020-02-29T16:00:00.000Z&end_time=2020-03-23T08:57:04.428Z
Authorization: {{authorization}}
Accept: application/json

###



# ----------------------------pcap--------------------------



###

POST http://{{host}}:{{port}}/api/v1/devicepcap/pcap/
Authorization: {{authorization}}
Accept: application/json

{"start_time":"2020-01-31T18:40:00.000Z","end_time":"2020-04-30T06:40:00.000Z","device_address":[],
"dst_ip":"1.1.1.1","mode":"r,d,t","protocol":"tcp","num":10}

###

GET http://{{host}}:{{port}}/api/v1/devicepcap/?status=1
Authorization: {{authorization}}
Accept: application/json


###
GET http://{{host}}:{{port}}/api/v1/globalmonitor/linescopemonitor/cleandevicepcaptask/?customer_line_id=1
Authorization: {{authorization}}
Accept: application/json

###
POST http://{{host}}:{{port}}/ads/pcap_single
Authorization: {{authorization}}
Accept: application/json

{"dst_ip": "1.1.1.1", "mode": "r,d,t", "protocol": "tcp", "num": 10, "duration": 11, "detail": [{"device_ip": "1.1.1.7"}, {"device_ip": "10.66.250.185"}], "creator": 1, "creator_ip": "10.66.40.61"}

###
GET http://{{host}}:{{port}}/api/v1/devicepcaptask/?status__in=2&limit=3&offset=0
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/devicepcaptask/3/download
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/devicepcaptask/4/downloadall
Authorization: {{authorization}}
Accept: application/json


###

POST http://{{host}}:{{port}}/api/v1/devicepcaptask/109/stop/
Authorization: {{authorization}}
Accept: application/json

###

POST http://{{host}}:{{port}}/api/v1/devicepcaptask/109/stop/
Authorization: {{authorization}}
Accept: application/json

###




# ----------------------------user--------------------------



###
###

GET http://{{host}}:{{port}}/api/v1/users
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/users/available
Authorization: {{authorization}}
Accept: application/json

###

PUT http://{{host}}:{{port}}/api/v1/users/1/
Authorization: {{authorization}}
Accept: application/json

{"is_staff":true,"is_superuser":false,"user_groups":[1],"username":"admin","account":"admin"}

###

POST http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/orders/1/stoporder/
Authorization: {{authorization}}
Accept: application/json

###

GET http://{{host}}:{{port}}/api/v1/billorders/?service_state=1&start_time=2020-04-21T06:25:00.356Z&end_time=2020-10-22T06:25:00.356Z&limit=10&offset=0
Authorization: {{authorization}}
Accept: application/json

###
# ----------------------------dnstrack--------------------------

###

GET http://{{host}}:{{port}}/api/v1/dnstracktrend/?rule_id=4&start_time=2020-03-31T10:22:56.970Z&end_time=2020-03-31T19:22:56.970Z
Authorization: {{authorization}}
Accept: application/json

###

###

POST http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/dnstrackrules/
Authorization: {{authorization}}
Accept: application/json

{"track_method":0,"protocol":"http","customer_line":"1","domain":"www.google.com","original_ip":["122.21.1.1"]}

###

# ----------------------------devices--------------------------

###

GET http://{{host}}:{{port}}/api/v1/devices/ads/?scrubbing_monitor_point=1
Authorization: {{authorization}}
Accept: application/json

###


POST http://{{host}}:{{port}}/api/v1/devices/nta/divertconfig/
Authorization: {{authorization}}
Accept: application/json

{"ipranges":["122.21.0.0"],"is_default":false,"device":1,"daemon": "adbostest"}

###
###

GET http://{{host}}:{{port}}/api/v1/devices/nta/divertconfig/
Authorization: {{authorization}}
Accept: application/json

###

# ----------------------------test--------------------------

POST https://10.66.242.125/devicelog
Authorization: {{authorization}}
Content-Type: application/json

{}

###


###

# ----------------------------mitigation/block--------------------------

POST http://{{host}}:{{port}}/api/v1/adsblockip/start/
Content-Type: application/json
Authorization: {{authorization}}

{
  "dstip": "122.21.1.1",
  "keep_time_seconds": 60,
  "scrubbing_monitor_group": "1"
}

###

POST http://{{host}}:{{port}}/api/v1/ntablockip/start/
Content-Type: application/json
Authorization: {{authorization}}

{
  "dstip": "1.1.1.1",
  "keep_time_seconds": 60,
  "type": 1,
  "scrubbing_monitor_group": "1"
}

###

###

# ----------------------------mitigation/block--------------------------


###
POST http://{{host}}:{{port}}/api/v1/customergroups/
Content-Type: application/json
Authorization: {{authorization}}

{
  "name": "1112311111",
  "users": [
    4,
    5
  ]
}

###

###

# ----------------------------report--------------------------

###

POST http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/1/report/1/download/
Content-Type: application/json
Authorization: {{authorization}}

{
  "name": "test",
  "scrubbing_monitor_group": "1",
  "scrubbing_monitor_group_dashboard": 3,
  "scrubbing_monitor_point_id": 1,
  "format": "html",
  "start_time": "2020-03-31T16:00:00.000Z",
  "end_time": "2020-04-30T15:59:59.999Z"
}

###

###



# ----------------------------audit--------------------------



###
GET http://{{host}}:{{port}}/api/v1/audit/?limit=10&offset=0&username=admin
Content-Type: application/json
Authorization: {{authorization}}

###


# ----------------------------devices--------------------------

###
GET http://{{host}}:{{port}}/api/v1/notices/?limit=10&offset=0&username=admin
Content-Type: application/json
Authorization: {{authorization}}

###


# ----------------------------strategy--------------------------

###
PUT http://{{host}}:{{port}}/api/v1/scrubbingzones/undefined/defaultddospolicy/98/
Content-Type: application/json
Authorization: {{authorization}}

{
  "id": 98,
  "name": "test_strategy_pg",
  "description": null,
  "date_created": "2020-06-16T02:27:34.164414Z",
  "date_changed": "2020-06-16T02:27:34.164414Z",
  "threshold": null,
  "state": "OK",
  "template": null,
  "revision": {
    "id": 81,
    "date_created": "2020-06-16T02:27:34.164414Z",
    "state": "ACTIVE",
    "creator": "admin",
    "policy": {
      "DDOS": {
        "SYN": {
          "level": "Default",
          "conf_1": 2001,
          "conf_2": "2000",
          "direction": "1",
          "algorith": "1"
        },
        "ACK": {
          "level": "Default",
          "conf_1": "8000",
          "direction": "1"
        },
        "UDP": {
          "level": "Default",
          "conf_1": "1000",
          "direction": "64"
        },
        "ICMP": {
          "level": "Default",
          "conf_1": "4000",
          "direction": "1"
        },
        "CC": {
          "conf_1": "1000",
          "direction": "1",
          "algorith": "1"
        },
        "POST": {
          "conf_1": "1000",
          "direction": "1",
          "algorith": "2"
        },
        "HTTP_PORT": {
          "port": "80"
        }
      },
      "FLAGSET": {
        "TCP": {
          "syn_band_limit": "0",
          "tcp_reset_limit": "100000",
          "band_limit_value": "0",
          "syn_resend_check": "0",
          "tcp_target": "0",
          "ack_algorithm": "0",
          "ack_learn_switch": "0",
          "ack_retrans_min_jiffies": "8",
          "ack_retrans_max_jiffies": "24",
          "tcp_fragment": "1"
        },
        "TRUSTIP": {
          "enable": "0",
          "policy": "0",
          "syn_pps": "100",
          "get_pps": "50",
          "ack_pps": "100",
          "other_pps": "100",
          "empty_conn": "0"
        }
      },
      "DNS": {
        "query_pt": "0",
        "query_level": "0",
        "algorith": "0",
        "reverse_detection": "0"
      },
      "UDP": {
        "udp_fragment": "1",
        "src_limit_level": "0",
        "udp_min_len": "0",
        "udp_len": "65535",
        "sip_port_tc_enable": "0",
        "sip_port_tc_max": "65535",
        "sip_tc_enable": "0",
        "sip_tc_max": "3000000",
        "dip_port_tc_enable": "0",
        "dip_port_tc_max": "65535",
        "disp_port_tc_enable": "0",
        "disp_port_tc_max": "65535",
        "dip_tc_enable": "0",
        "dip_tc_max": "3000000"
      },
      "ICMP": {
        "icmp_srcip_limit_enable": "0",
        "icmp_srcip_limit": "3000000",
        "icmp_dstip_limit_enable": "0",
        "icmp_dstip_limit": "3000000",
        "icmp_fragment": "1"
      }
    },
    "pg_name": "test_strategy_pg",
    "pg_id": 98
  },
  "scrubbing_monitor_group": null,
  "scrubbing_monitor_point": null,
  "scrubbing_zone": {
    "id": 44,
    "name": "test_strategy",
    "description": null,
    "scrubbing_environment": 17,
    "scheme": 1
  },
  "scrubbing_node": null
}

###


# ----------------------------rule--------------------------


###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/17/fusing/
Content-Type: application/json
Authorization: {{authorization}}

###
POST http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/20/fusing/
Content-Type: application/json
Authorization: {{authorization}}

{
  "device_type": "ads"
}

###
DELETE http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/20/fusing/6/
Content-Type: application/json
Authorization: {{authorization}}

###


# ----------------------------api--------------------------


###
GET http://{{host}}:{{port}}/api/v1/currentuser/
Content-Type: application/json
Authorization: {{authorization}}



###
GET http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/10/eventautodispatchpolicy/
Content-Type: application/json
Authorization: {{authorization}}


###
PUT http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/10/eventautodispatchpolicy/10/
Content-Type: application/json
Authorization: {{authorization}}

{
  "is_default": true,
  "policy_type": "nta_bgpflowspec",
  "min_threshold_bps": 1,
  "keep_time_seconds": "101",
  "priority_level": 1,
  "dstip": "0.0.0.0",
  "threshold_cond": "2",
  "scrubbing_monitor_group": 10,
  "max_threshold_bps": null,
  "advanced_config_enable": true,
  "advanced_config": {
    "action_type": "accept",
    "action_value": null
  }
}

###



# ----------------------------fusing--------------------------



###
POST http://{{host}}:{{port}}/api/v1/scrubbingmonitorgroups/5/fusing/
Content-Type: application/json
Authorization: {{authorization}}

{
  "scrubbing_monitor_group": 5,
  "device_type": "ads",
  "fuse": "START_BLOCK",
  "fusing_threshold": 11,
  "fusing_time": 11,
  "white_list": [
    "1.1.1.1"
  ],
  "force_fusing_threshold": 13,
  "fusing_num": "1",
  "is_reverse": false,
  "enable": true
}

###